services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: shortener
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: shortener
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: development
      HTTP_PORT: 8080

      # MySQL
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: shortener
      DB_PASS: secret
      DB_NAME: shortener

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Security & Rate Limiting
      JWT_SECRET: StzoBbz5NqyJprT4fBa9CpEqdUMtb9v1kNC7lfPlAdc=
      RATE_LIMIT_REQUESTS: 100
      RATE_LIMIT_WINDOW: 60

    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ../backend/.env:/root/.env

volumes:
  mysql-data:
